import { test, expect } from "bun:test";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createFakeBlobStore } from "@/archive/blob";
import {
  renderMarkdown,
  persist,
  dayWindows,
  mergeCounts,
  type TrafficReport,
} from "../scripts/analytics-report";

const zoneReport: TrafficReport = {
  generatedAt: "2026-07-15T00:00:00.000Z",
  window: { sinceDate: "2026-07-08", untilDate: "2026-07-15", days: 7 },
  seenZoneCount: 1,
  zones: [
    {
      name: "thegarlictimes.com",
      id: "zone1",
      pageViews: 100,
      uniques: 40,
      requests: 250,
      topPages: [{ path: "/", count: 60 }],
      topCountries: [{ country: "United States", count: 120 }],
    },
  ],
  referrers: null,
  totals: { pageViews: 100, uniques: 40 },
};

test("dayWindows enumerates one <=1-day UTC window per calendar day, inclusive", () => {
  const since = new Date("2026-07-12T12:00:00Z");
  const until = new Date("2026-07-15T09:30:00Z");
  const windows = dayWindows(since, until);

  expect(windows.map((w) => w.date)).toEqual([
    "2026-07-12",
    "2026-07-13",
    "2026-07-14",
    "2026-07-15",
  ]);
  expect(windows[0]).toEqual({
    date: "2026-07-12",
    startTime: "2026-07-12T00:00:00Z",
    endTime: "2026-07-12T23:59:59Z",
  });
  // Every window must be strictly under 1 day wide — the plan's hard limit.
  for (const w of windows) {
    expect(Date.parse(w.endTime) - Date.parse(w.startTime)).toBeLessThan(24 * 60 * 60 * 1000);
  }
});

test("mergeCounts sums counts per key across days, sorts desc, keeps top N", () => {
  const merged = mergeCounts(
    [
      { key: "/", count: 10 },
      { key: "/about", count: 3 },
      { key: "/", count: 5 }, // same key, another day
      { key: "/2026-07-14", count: 8 },
    ],
    2,
  );
  expect(merged).toEqual([
    { key: "/", count: 15 },
    { key: "/2026-07-14", count: 8 },
  ]);
});

test("renderMarkdown is byte-for-byte stable for a zone report", () => {
  const expected = [
    "## Traffic baseline — 2026-07-08 → 2026-07-15 (7d)",
    "",
    "_Source: Cloudflare zone analytics (cookieless, server-side). Generated by `scripts/analytics-report.ts`._",
    "",
    "### thegarlictimes.com",
    "",
    "| Metric | Last 7d |\n| --- | --- |\n| Page views | 100 |\n| Unique visitors | 40 |\n| Total requests | 250 |",
    "",
    "**Top pages**",
    "| Path | Views |\n| --- | --- |\n| / | 60 |",
    "",
    "**Top countries**",
    "| Country | Requests |\n| --- | --- |\n| United States | 120 |",
    "",
    "### Top referrers (Web Analytics / RUM)",
    "",
    "_Not available yet — enable Cloudflare Web Analytics (set `CF_BEACON_TOKEN`) and allow ~1 week of data. See docs/analytics.md._",
    "",
    "**Totals across zones:** 100 page views · 40 unique visitors (last 7d).",
  ].join("\n");
  expect(renderMarkdown(zoneReport)).toBe(expected);
});

test("persist writes raw JSON, the report markdown, and prepends to the rolling log", async () => {
  const backing = mkdtempSync(join(tmpdir(), "gt-analytics-"));
  const store = createFakeBlobStore(backing);

  const md1 = renderMarkdown(zoneReport);
  await persist(store, zoneReport, md1);

  // raw JSON round-trips back to the report object.
  const rawJson = await store.downloadText("raw/2026-07-15.json");
  expect(rawJson).not.toBeNull();
  expect(JSON.parse(rawJson!)).toEqual(zoneReport);

  // human-readable per-run report is the same markdown.
  expect(await store.downloadText("reports/2026-07-15.md")).toBe(md1);

  // a second run for a later date lands newest-first above the first.
  const secondReport: TrafficReport = {
    ...zoneReport,
    window: { sinceDate: "2026-07-15", untilDate: "2026-07-22", days: 7 },
  };
  const md2 = renderMarkdown(secondReport);
  await persist(store, secondReport, md2);

  const log = await store.downloadText("traffic-log.md");
  expect(log).not.toBeNull();
  expect(log!.indexOf(md2)).toBeLessThan(log!.indexOf(md1));
  expect(log!).toContain("# Traffic log");
});
